import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Custom sidebar to show modules first, then tutorials
  docs: [
    {
      type: 'category',
      label: 'Getting Started',
      items: ['intro', 'personalization-example'],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 1: ROS2 Nervous System',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module1-ros2-nervous-system',
        },
      ],
      className: 'module-1',
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 2: Digital Twin',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module2-digital-twin',
        },
      ],
      className: 'module-2',
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 3: AI Robot Brain',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module3-ai-robot-brain',
        },
      ],
      className: 'module-3',
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 4: Vision Language Action',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module4-vision-language-action',
        },
      ],
      className: 'module-4',
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 5: Capstone & Future Directions',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module5-capstone-future-directions',
        },
      ],
      className: 'module-5',
      collapsed: false,
    },
  ],
};

export default sidebars;
