"""Add background information fields to user table

Revision ID: 9d4b26d74890
Revises: 
Create Date: 2025-12-11 16:26:42.491106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '9d4b26d74890'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_embedding_documents_id', table_name='embedding_documents')
    op.drop_table('embedding_documents')
    op.drop_index('ix_lesson_sections_id', table_name='lesson_sections')
    op.drop_table('lesson_sections')
    op.drop_index('ix_ingestion_jobs_id', table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_index('ix_book_metadata_id', table_name='book_metadata')
    op.drop_table('book_metadata')
    op.drop_index('ix_lessons_id', table_name='lessons')
    op.drop_table('lessons')
    op.drop_index('ix_api_usage_quotas_id', table_name='api_usage_quotas')
    op.drop_table('api_usage_quotas')
    op.drop_index('ix_chapters_id', table_name='chapters')
    op.drop_table('chapters')
    op.drop_index('ix_chat_history_id', table_name='chat_history')
    op.drop_index('ix_chat_history_session_id', table_name='chat_history')
    op.drop_table('chat_history')
    op.drop_index('ix_notes_id', table_name='notes')
    op.drop_table('notes')
    op.drop_index('ix_rag_queries_id', table_name='rag_queries')
    op.drop_table('rag_queries')
    op.drop_index('ix_highlights_id', table_name='highlights')
    op.drop_table('highlights')
    op.add_column('users', sa.Column('software_background_level', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('hardware_background_level', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('preferred_languages', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('learning_goals', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'learning_goals')
    op.drop_column('users', 'preferred_languages')
    op.drop_column('users', 'hardware_background_level')
    op.drop_column('users', 'software_background_level')
    op.create_table('highlights',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('content_id', sa.INTEGER(), nullable=False),
    sa.Column('content_type', sa.VARCHAR(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('start_pos', sa.INTEGER(), nullable=False),
    sa.Column('end_pos', sa.INTEGER(), nullable=False),
    sa.Column('note', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_highlights_id', 'highlights', ['id'], unique=False)
    op.create_table('rag_queries',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('query_text', sa.TEXT(), nullable=False),
    sa.Column('response_text', sa.TEXT(), nullable=False),
    sa.Column('context_chunks', sqlite.JSON(), nullable=False),
    sa.Column('tokens_used', sa.INTEGER(), nullable=False),
    sa.Column('response_time_ms', sa.INTEGER(), nullable=False),
    sa.Column('is_hallucination', sa.BOOLEAN(), nullable=False),
    sa.Column('feedback_score', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rag_queries_id', 'rag_queries', ['id'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('content_id', sa.INTEGER(), nullable=False),
    sa.Column('content_type', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('is_public', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notes_id', 'notes', ['id'], unique=False)
    op.create_table('chat_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('session_id', sa.VARCHAR(), nullable=False),
    sa.Column('role', sa.VARCHAR(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_history_session_id', 'chat_history', ['session_id'], unique=False)
    op.create_index('ix_chat_history_id', 'chat_history', ['id'], unique=False)
    op.create_table('chapters',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('order_index', sa.INTEGER(), nullable=False),
    sa.Column('book_metadata_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['book_metadata_id'], ['book_metadata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chapters_id', 'chapters', ['id'], unique=False)
    op.create_table('api_usage_quotas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('quota_type', sa.VARCHAR(), nullable=False),
    sa.Column('quota_limit', sa.INTEGER(), nullable=False),
    sa.Column('quota_used', sa.INTEGER(), nullable=False),
    sa.Column('quota_period_start', sa.DATETIME(), nullable=False),
    sa.Column('reset_interval_hours', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_api_usage_quotas_id', 'api_usage_quotas', ['id'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('order_index', sa.INTEGER(), nullable=False),
    sa.Column('chapter_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lessons_id', 'lessons', ['id'], unique=False)
    op.create_table('book_metadata',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('version', sa.VARCHAR(), nullable=False),
    sa.Column('total_chapters', sa.INTEGER(), nullable=False),
    sa.Column('total_lessons', sa.INTEGER(), nullable=False),
    sa.Column('total_words', sa.INTEGER(), nullable=False),
    sa.Column('language', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_book_metadata_id', 'book_metadata', ['id'], unique=False)
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('job_id', sa.VARCHAR(), nullable=False),
    sa.Column('admin_user_id', sa.INTEGER(), nullable=True),
    sa.Column('file_path', sa.VARCHAR(), nullable=False),
    sa.Column('file_name', sa.VARCHAR(), nullable=False),
    sa.Column('file_type', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('total_chunks', sa.INTEGER(), nullable=True),
    sa.Column('processed_chunks', sa.INTEGER(), nullable=False),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=False),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index('ix_ingestion_jobs_id', 'ingestion_jobs', ['id'], unique=False)
    op.create_table('lesson_sections',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('order_index', sa.INTEGER(), nullable=False),
    sa.Column('lesson_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lesson_sections_id', 'lesson_sections', ['id'], unique=False)
    op.create_table('embedding_documents',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('qdrant_id', sa.VARCHAR(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('content_type', sa.VARCHAR(), nullable=False),
    sa.Column('content_id', sa.INTEGER(), nullable=False),
    sa.Column('doc_metadata', sqlite.JSON(), nullable=False),
    sa.Column('embedding_model', sa.VARCHAR(), nullable=False),
    sa.Column('tokens', sa.INTEGER(), nullable=False),
    sa.Column('chapter_id', sa.INTEGER(), nullable=True),
    sa.Column('lesson_id', sa.INTEGER(), nullable=True),
    sa.Column('lesson_section_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['lesson_section_id'], ['lesson_sections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qdrant_id')
    )
    op.create_index('ix_embedding_documents_id', 'embedding_documents', ['id'], unique=False)
    # ### end Alembic commands ###
